
from skspatial.typing import array_like


class Axes:

    def add_artist(self, obj: object) -> None: ...
    def arrow(self, x: float, y: float, dx: float, dy: float, **kwargs: float) -> None: ...
    def plot(self, *args: array_like, **kwargs: str) -> None: ...
    def scatter(self, x: array_like, y: array_like, **kwargs: str) -> None: ...
