from typing import Any, Sequence

class Axes:

    def add_artist(self, obj: Any) -> None: ...
    def arrow(self, x: float, y: float, dx: float, dy: float, **kwargs: float) -> None: ...
    def plot(self, *args: Sequence, **kwargs: str) -> None: ...
    def scatter(self, x: Sequence, y: Sequence, **kwargs: str) -> None: ...
