from typing import Sequence


class Axes3D:

    def plot(self, xs: Sequence, ys: Sequence, zs: Sequence, **kwargs: str) -> None: ...
    def plot_surface(self, X: Sequence, Y: Sequence, Z: Sequence, *args: float, **kwargs: float) -> None: ...
    def scatter(self, xs: Sequence, ys: Sequence, zs: Sequence, **kwargs: str) -> None: ...
