
from skspatial.typing import array_like


class Axes3D:

    def plot(self, xs: array_like, ys: array_like, zs: array_like, **kwargs) -> None: ...
    def plot_surface(self, X: array_like, Y: array_like, Z: array_like, *args, **kwargs) -> None: ...
    def scatter(self, xs: array_like, ys: array_like, zs: array_like, **kwargs) -> None: ...
