name: publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.18"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install tox
        run: uv tool install tox --with tox-uv --with tox-gh

      - name: Run tox
        run: tox

      - name: Build and publish to PyPI
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}
